# Generated by Django 4.2.1 on 2023-05-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('gamebasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.gamebasemodel')),
            ],
            bases=('game.gamebasemodel',),
        ),
    ]
