# Generated by Django 4.2.1 on 2023-05-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(default=123, max_length=254),
            preserve_default=False,
        ),
    ]
