# Generated by Django 4.2.1 on 2023-05-07 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(max_length=256, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
