# Generated by Django 4.2.1 on 2023-05-07 21:41

import django.core.validators
from django.db import migrations, models
import student_management.students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, validators=[student_management.students.validators.profile_name_validator]),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, validators=[student_management.students.validators.profile_name_validator]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(max_length=256),
        ),
    ]
