# Generated by Django 4.2.2 on 2023-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('year_of_manufacturing', models.PositiveIntegerField()),
            ],
        ),
    ]
