# Generated by Django 4.2.2 on 2023-06-19 16:31

import django.core.validators
from django.db import migrations, models
import exam_prep1.plant_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Outdoor', 'Outdoor'), ('Plants', 'Plants'), ('Indoor Plants', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), exam_prep1.plant_app.validators.plant_name_validator])),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
