# Generated by Django 4.2.2 on 2023-06-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmodel',
            name='type',
            field=models.CharField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Indoor Plants', 'Indoor Plants')], max_length=14),
        ),
    ]
