# Generated by Django 4.2.2 on 2023-06-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0002_alter_plantmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmodel',
            name='price',
            field=models.FloatField(verbose_name='Price:'),
        ),
    ]
