# Generated by Django 4.2.1 on 2023-05-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant',
            new_name='PlantModel',
        ),
    ]
