# Generated by Django 4.2.1 on 2023-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_app', '0003_alter_plantmodel_description_alter_plantmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmodel',
            name='plant_type',
            field=models.CharField(choices=[('outdoor', 'Outdoor Plants'), ('indoor', 'Indoor Plants')], max_length=14, verbose_name='Type:'),
        ),
    ]
