# Generated by Django 4.2.1 on 2023-05-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
