# Generated by Django 4.2.1 on 2023-05-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_departments_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='departments',
            new_name='department',
        ),
    ]
