# Generated by Django 4.2.1 on 2023-06-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='image_url',
            field=models.URLField(verbose_name='Link to image'),
        ),
    ]
